const KEY = /^[A-Za-z0-9][A-Za-z0-9._\-]*(\/[A-Za-z0-9][A-Za-z0-9._\-]*)*$/;

/** Object keys are generated by us from UUIDs and fixed names; anything else is a bug or an attack. */
export function assertValidKey(key: string): void {
  if (key.length === 0 || key.length > 512 || !KEY.test(key) || key.split('/').some((seg) => seg === '..' || seg === '.')) {
    throw new Error(`Invalid object key: ${JSON.stringify(key.slice(0, 80))}`);
  }
}
