-- Phase 5a decision 1: Better Auth identity tables, in their own schema so public-schema guards stay unchanged.
-- Generated by better-auth@1.7.7 getMigrations().compileMigrations(); never edited by Better Auth at runtime.
CREATE SCHEMA IF NOT EXISTS auth;
--> statement-breakpoint
create table "auth"."user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);
--> statement-breakpoint
create table "auth"."session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "auth"."user" ("id") on delete cascade);
--> statement-breakpoint
create table "auth"."account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "auth"."user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);
--> statement-breakpoint
create table "auth"."verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);
--> statement-breakpoint
create table "auth"."rateLimit" ("id" text not null primary key, "key" text not null unique, "count" integer not null, "lastRequest" bigint not null);
--> statement-breakpoint
create index "session_userId_idx" on "auth"."session" ("userId");
--> statement-breakpoint
create index "account_userId_idx" on "auth"."account" ("userId");
--> statement-breakpoint
create index "verification_identifier_idx" on "auth"."verification" ("identifier");
--> statement-breakpoint
-- Emails are compared case-insensitively everywhere (invitations, contacts).
create index "user_email_lower_idx" on "auth"."user" (lower("email"));
--> statement-breakpoint
-- Only the service role (Better Auth's connection, @cs/tools) touches auth.*; app_user gets nothing.
GRANT USAGE ON SCHEMA auth TO app_service;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA auth TO app_service;
--> statement-breakpoint
ALTER TABLE membership ADD CONSTRAINT membership_user_id_fk FOREIGN KEY (user_id) REFERENCES auth."user"(id) ON DELETE CASCADE;
